# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b47b02ac77be638ddac5619330179f2a5f7775c686ab7b993d9323c0c610caedfb5f16b268ce8bacecc0efea04e11f0ad66d4a3dff6545377b8ea5566d134d9

test:
  secret_key_base: 3aaa6bea9e2906004122866f4db1b3d3cf51341b9343816f5af851bd3baf53a5ae7e377dc99f82955db69d421125276366f4dd6c9e24ff0e1967bf6ec0e186d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
